[package]
name = "tonearm"
version = "0.1.0"
description = "A fast native desktop client for Navidrome and Jellyfin"
authors = ["Tonearm contributors"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
window-vibrancy = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
